### ISSUE TITLE
rename summarize_run to match tiled/bluesky nomenclature

### ISSUE THREAD

**Issue by EliotGann** [usnistgov/PyHyperScattering#103]
run has a specific meaning the the bluesky tiled environment, which can cause confusion in this context.  A more appropriate name might be search_catalog or something similar.  @BijalBPatel please comment

**Comment by EliotGann** [comment]
https://github.com/usnistgov/PyHyperScattering/blob/6e26f4c64a811eb70bd096b7d32eec4c50a847aa/src/PyHyperScattering/SST1RSoXSDB.py#L134

**Comment by BijalBPatel** [comment]
Totally agree - i was thinking search_catalog is a good name as well. I can take this on.

**Comment by pbeaucage** [comment]
I like this name too, one request, it should probably be typeset `searchCatalog` to match the rest of the methods of that class.

Also, if you leave a stub in for `summarize_run` something like:

```
def summarize_run(*args,**kwargs):
    warnings.warn('summarize_run has been renamed to searchCatalog.  This will stop working in PyHyperScattering 1.0.0 and later.',DeprecationWarning,stacklevel=2)
    return searchCatalog(*args,**kwargs)
```
It would be a kind thing to do.

**Comment by BijalBPatel** [comment]
I think catalog is a good mix of approachable (e.g., library catalog) and consistent with the Bluesky syntax. 
Feels like we've entered the 'good enough' zone where tutorials and docs can clear up the confusion.

**Comment by EliotGann** [comment]
yeah, I buy that.  personally I like verbose names but "search_catalog_for_experimental_run_summary" is probably a little bulky
