### ISSUE TITLE
Energy axis not working right with modern data (sst databroker module)

### ISSUE THREAD

**Issue by EliotGann** [usnistgov/PyHyperScattering#21]
I'm not sure what is going on exactly, but I have to run a command like this to clean up and use the energy axis with data taken recently.
the fix right now it this:
ens = raw.energy
energies = ens.values[0:-1]
reduceddata = integrated.rename({'system': 'energy'}).reset_index('energy').reset_coords(drop=True).assign_coords({'energy':energies})

**Comment by pbeaucage** [comment]
I believe this is the same issue as one I just fixed where the last energy of the scan is repeated.

**Comment by pbeaucage** [comment]
This seems to have been fixed in 2263cb2.
