### ISSUE TITLE
test how import works with energy and polarization/angle within a single bluesky run

### ISSUE THREAD

**Issue by EliotGann** [usnistgov/PyHyperScattering#63]
SST1's new acquisition scheme will allow for multiple energy scans in a single run.  how these will import into pyhyper will be important to rigorously test

**Comment by pbeaucage** [comment]
do you have an example scan id?

**Comment by EliotGann** [comment]
I solved this for my Igor browser.  it's slightly painful, but my logic is 1.) check if axis exists, if it exists, check if the maximum and minimum are more than 0.1 apart.  if so, add that as an axis.  if not, just make it a variable

**Comment by EliotGann** [comment]
48815 -> energy and polarization
48813 ->polarization
48812 -> angle and polarization (also sample x and y, but in such cases angle is the main one)

**Comment by EliotGann** [comment]
energy could be an added axis in either of those last two (it's just one value in these cases)

**Comment by cbishop4** [comment]
Working on this issue - to clarify, for scan 48815, it has been taken at several energies (typical) and also multiple (I'm assuming 2) polarizations (new)? 48813 was taken at multiple polarizations, with no other changes - i.e., was taken at a single energy? And 48812 was taken at a single energy, but with multiple angles and polarizations?

**Comment by EliotGann** [comment]
That's what I meant, yes.  Energy can be an axis in most scans, then extra axes that have been added immediately are polarization and angle (which also moves X and Y).  then we need to also handle Spiral scans, where X and Y are changed but there is only one energy, polarization, and angle.  I can link to where I handle this in the Igor reader if that helps with the logic.

**Comment by EliotGann** [comment]
https://github.com/NSLS-II-SST/TiledRSoXS/blob/33f1d34056bbb849c0db6f0482367158585f95ce/TiledRSoXS.ipf#L849-L894
 is where I do the logic of naming the images based on if each of the axes exist, and if they deviate more than 0.1.

**Comment by pbeaucage** [comment]
I'm going to leave this open for a critical issue: we should really have unit tests in the code of all these odd loading scenarios, even if we have to mark them skipped until public Tiled server is available.

**Comment by pbeaucage** [comment]
@cbishop4 and @EliotGann - scan 48815 is a NEXAFS scan.  Is there an equivalent RSoXS scan for testing?

**Comment by pbeaucage** [comment]
This is now completed in PR #65.  Seems to work well.
