### ISSUE TITLE
ALS 11.0.1.2 file loader - change in "shutter inhibit" name

### ISSUE THREAD

**Issue by mrlandsman** [usnistgov/PyHyperScattering#64]
Within ALS11012RSoXSloader.py, the shutter inhibit is defined as `'CCD Shutter Inhibit'`, but more-recent data collected at 11.0.1.2 use `'CCD Camera Shutter Inhibit` instead. Cheng said he thinks this change in the variable name occurred in March 2021 when the camera driver was updated. Can you implement a universal lookup for defining the correct shutter inhibit column name for datasets pre- and post-March 2021?

**Comment by pbeaucage** [comment]
Thanks for the issue, Matt!

I have a tentative fix for this using a flag in the linked branch.
I'd like to add an automated test for this as well.  To do this well, I should really add an example newer dataset to the testing data pack.  Would you be willing to share a short scan taken on 11.0.1.2 after the change?  This data would be publicly hosted in this Git project.  We could strip identifying information if you wish.

**Comment by mrlandsman** [comment]
Thanks for the fix, Peter! I'm attaching a folder with a short (3 energy) carbon edge scan of 300 nm polystyrene spheres that I collected a few days ago. Please let me know if there's anything else I can provide/help with. 

[PSS300nm_C_ccd100.zip](https://github.com/usnistgov/PyHyperScattering/files/10886303/PSS300nm_C_ccd100.zip)
