### ISSUE TITLE
feat: Add converter back/forth between pix_x/pix_y axes and q_x/q_y space

### ISSUE THREAD

**Issue by pbeaucage** [usnistgov/PyHyperScattering#7]
This shouldn't be terribly hard, in fact @pdudenas already did this in some form in his original SST1 loader.

This will be required for two down-stream features:

1) a loader for Cy-RSoXS simulation data, which is inherently in qx/qy space (the loader could just handle the conversion, but this seems silly... shared code)

2) writing detector images as 2d-calibrated NeXus files, which by convention use qx/qy coordinates.

This should probably be in a utility module.

Some design questions remain: do we have a most-favored-format (i.e, is qx/qy always a stepchild?).  I could plausibly see integrators, esp. those based on pyfai, really wanting to live in pixel space.  Perhaps these converter utilities are invoked transparently and we just warn: hey, pyfai is really not the best integrator for qx/qy data.

**Comment by pdudenas** [comment]
An update on this: I tried to add a flag in the loader stage, but because q changes with energy it blows up the memory needed. Seems like the same sort of thing that makes the multi-index necessary.

Would this be good to add in through the xarray extension? Create a new method called something like 'qplot()'?

**Comment by pbeaucage** [comment]
Give the version on the qxy branch a try?  I added some logic to the stacker that tries to reinterpolate when stacking.

**Comment by pbeaucage** [comment]
this has been addressed in the new qxy features - PR #15
