### ISSUE TITLE
Build tests for SST1RSoXSDB loader

### ISSUE THREAD

**Issue by pbeaucage** [usnistgov/PyHyperScattering#70]
For a long time there have been no CI tests for the SST1RSoXSDB loader, because this loader requires a connection to `tiled.nsls2.bnl.gov` which is only accessible inside the Brookhaven firewall.  However, given that this is both a growing part of the codebase and one where there are frequent metadata changes that break the loader AND required support for historical data, I think having some tests is prudent.

We should be able to use `pytest.skipif()` to turn the tests off when running on GitHub Actions and back on when running on a machine inside BNL.  Eventually, these will be turned on for the whole test suite.

**Comment by EliotGann** [comment]
there is the tiled public test server that could work very well for this.  We can get dan to load some examples datasets, if we identify the scan IDs that we want.

**Comment by danielballan** [comment]
Yes, I would be happy to do this.

And, later, when tiled.nsls2.bnl.gov is available outside the firewall, I could imagine making a portion of that fully public, or accessible with an API key designated for this project.
